name: Yotta CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 2.7.x
      uses: actions/setup-python@v2
      with:
        python-version: '2.7.x'
    - name: Update packages
      run: sudo apt-get update
    - name: Install Ninja
      run: sudo apt-get install ninja-build -y
    - name: Install Yotta
      run: sudo pip install yotta
    - name: Build
      run: yotta build
